### PR TITLE
[CI][arm] Fix tensorflow-aarch64 repository URL

### LINKED ISSUE #11773: [ci] ci_arm container build fails
ci_arm is [failing to build](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11772/4/pipeline/).

Looks like the version of tensorflow-aarch64 has gone missing from the aarch64 pip repo: https://snapshots.linaro.org/ldcg/python-cache/tensorflow-aarch64/

cc @Mousius @driazati @gromero @leandron

### PR DESCRIPTION
**Pull request by leandron**
Update the custom repository URL used to pull TensorFlow-aarch64. The mechanism of installation is also changed to a file based, as a temporary workaround before we update to a newer version (>=2.7) that can be pulled from the official PyPI repository.

Closes #11773

cc @Mousius @areusch @lhutton1 @driazati

### CODE REVIEW

File: docker/install/ubuntu_install_tensorflow_aarch64.sh [hunk 1]
```diff
@@ -21,11 +21,26 @@ set -euxo pipefail
...
+tensorflow_package="tensorflow_aarch64-2.6.3-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
+tmpdir=$(mktemp -d)
+
+cleanup()
+{
+  rm -rf "$tmpdir"
+}
+
+trap cleanup 0
+
```
Comment (leandron) [inline docker/install/ubuntu_install_tensorflow_aarch64.sh:37]: I'm missing to `cd` into my tmpdir. I will update this once I test the change.

**Review by lhutton1 — APPROVED** [review]
Thanks @leandron for the quick fix!

**Comment by driazati** [comment]
@tvm-bot rerun
