### PR TITLE
[microTVM] Fix host-driven AOT memory workspaces

### LINKED ISSUE #13777: [Bug][microTVM]Enabling USMP with VWW model has error
I tried to add a test that compiles VWW model with AOT in Zephyr to build with and without USMP, with USMP has error:

```14:46:53] /home/mhessar/work/tvm/src/runtime/micro/micro_session.cc:377: remote: input allocate[0]: input_1_int8
[14:46:53] /home/mhessar/work/tvm/src/runtime/micro/micro_session.cc:377: remote: output allocate[0]: output0
[14:46:53] /home/mhessar/work/tvm/src/runtime/micro/micro_session.cc:377: remote: pools allocate[0]: global_workspace_1_var
[14:46:53] /home/mhessar/work/tvm/src/runtime/micro/micro_session.cc:377: remote: CMAKE_SOURCE_DIR/crt/src/runtime/crt/aot_executor/aot_executor.c:216: Check failed: 0 == md->num_constant_pools: Constant pools not supported
[14:46:53] /home/mhessar/work/tvm/src/runtime/micro/micro_session.cc:377: remote: TVMError: 0x500
```

Here's a diff to reproduce this error:
https://github.com/apache/tvm/compare/main...mehrdadh:tvm:micro/zephyr_add_model_usmp?expand=1

cc @alanmacd @d-smirnov @gromero @leandron @mkatanbaf

### PR DESCRIPTION
**Pull request by alanmacd**
When using host-driven AOT with memory pools enabled, the workspace and constant memory were not properly supported. In order for them to work properly, the \_run function (typically tvmgen_default_run()) needed to be called instead of tvmgen_default___tvm_main__() in order to properly setup the memory workspace pointers.

fixes #13777

### CODE REVIEW

**Comment by leandron** [comment]
Cc @ashutosh-arm @d-smirnov

File: src/runtime/crt/aot_executor/aot_executor.c [hunk 1]
```diff
@@ -203,17 +203,6 @@ int TVMAotExecutor_Init(TVMAotExecutor* executor, TVMModuleHandle module_handle,
...
-    LOG_DEBUG("pools allocate[%d]: %s\n", i, md->workspace_pools[i].name);
-
-    status = TVMNDArray_Empty(md->workspace_pools[i].num_shape, md->workspace_pools[i].shape,
-                              md->workspace_pools[i].dtype, executor->device,
-                              &executor->args[arg_idx++]);
-    if (status != 0) {
-      return status;
-    }
-  }
-  CHECK_EQ(0, md->num_constant_pools, "Constant pools not supported");
```
Comment (ashutosh-arm) [inline src/runtime/crt/aot_executor/aot_executor.c:216]: Hi @alanmacd, LGTM overall. I am not sure about whether this check can be removed. @d-smirnov knows more about it, so I will leave it to him.

File: tests/python/unittest/test_micro_model_library_format.py [hunk 2]
```diff
@@ -618,7 +618,6 @@ def test_multiple_relay_modules_aot_graph():
 
     assert os.path.exists(os.path.join(extract_dir, "codegen", "host", "src", "mod1_lib0.c"))
     assert os.path.exists(os.path.join(extract_dir, "codegen", "host", "src", "mod1_lib1.c"))
-    assert os.path.exists(os.path.join(extract_dir, "codegen", "host", "src", "mod1_lib2.c"))
```
Comment (mehrdadh) [inline tests/python/unittest/test_micro_model_library_format.py:621]: Could you please comment why `mod2` is not generated anymore?

**Comment by mehrdadh** [comment]
Overall LGTM! I'll wait for @d-smirnov before merging it. Thanks @alanmacd!!

File: tests/python/unittest/test_micro_model_library_format.py (hunk 2 above)
Comment (alanmacd) [reply tests/python/unittest/test_micro_model_library_format.py:621]: The get_c_metadata() function was being added to the graph executor generated source files but never used.

File: src/runtime/crt/aot_executor/aot_executor.c (hunk 1 above)
Comment (d-smirnov) [inline src/runtime/crt/aot_executor/aot_executor.c:216]: @alanmacd, Could you please add a unit test to replace the removed check for constant pools.

Comment (alanmacd) [reply src/runtime/crt/aot_executor/aot_executor.c:216]: @d-smirnov I updated the` test_aot_executor_usmp_const_pool()` test to always enable USMP and now expect that to be successful

Comment (alanmacd) [reply src/runtime/crt/aot_executor/aot_executor.c:216]: Additionally, added @mehrdadh's test_model_with_usmp() test to further test USMP.

Comment (d-smirnov) [reply src/runtime/crt/aot_executor/aot_executor.c:216]: @alanmacd Thank you, Alan. I might be missing something but could you point out where the constant pools are initialised and passed to the main executor function? (It could be that the test might be giving false negative result)

Comment (alanmacd) [reply src/runtime/crt/aot_executor/aot_executor.c:216]: @d-smirnov running `pytest tests/python/unittest/test_crt.py -k test_aot_executor_usmp_const_pool` and keeping the temporary files around, the generated C code will contain the following lines in default_lib0.c, is that what you are asking about?
```
__attribute__((section(".rodata.tvm"), ))
static struct global_const_workspace {
  uint8_t fused_add_constant_let[2] __attribute__((aligned(16))); // 2 bytes, aligned offset: 0
} global_const_workspace = {
  .fused_add_constant_let = {
    0x08, 0x09
  },
};// of total size 2 bytes
TVM_DLL int32_t tvmgen_default___tvm_main__(TVMValue* args, int* type_code, int num_args, TVMValue* out_value, int* out_type_code, void* resource_handle);

int32_t tvmgen_default_run(TVMValue* args, int* type_code, int num_args, TVMValue* out_value, int* out_type_code, void* resource_handle) {
TVMValue tensors[4];
tensors[0] = ((TVMValue*)args)[0];
tensors[1] = ((TVMValue*)args)[1];
tensors[2] = ((TVMValue*)args)[2];
DLTensor global_const_workspace_dltensor = {
.data = &global_const_workspace
};
TVMValue global_const_workspace_tvm_value = {
.v_handle = &global_const_workspace_dltensor
};
tensors[3] = global_const_workspace_tvm_value;
return tvmgen_default___tvm_main__((void*)tensors, type_code, num_args, out_value, out_type_code, resource_handle);
}
```

Comment (d-smirnov) [reply src/runtime/crt/aot_executor/aot_executor.c:216]: Thanks for clarifications @alanmacd

File: src/runtime/crt/aot_executor/aot_executor.c [hunk 3]
```diff
@@ -203,17 +203,6 @@ int TVMAotExecutor_Init(TVMAotExecutor* executor, TVMModuleHandle module_handle,
     TVMNDArray_IncrementReference(array);
   }
 
-  for (i = 0; i < md->num_workspace_pools; ++i) {
-    LOG_DEBUG("pools allocate[%d]: %s\n", i, md->workspace_pools[i].name);
-
-    status = TVMNDArray_Empty(md->workspace_pools[i].num_shape, md->workspace_pools[i].shape,
```
Comment (d-smirnov) [inline src/runtime/crt/aot_executor/aot_executor.c:209]: @alanmacd Should this be restored? (Along with TVMNDArray_IncrementReference(array) which is missing)

Comment (alanmacd) [reply src/runtime/crt/aot_executor/aot_executor.c:209]: @d-smirnov no, it doesn't make sense to allocate a workspace_pool, it will be in the generated C code similar to the const pool, there's an example below (I think I originally added the pool allocation and then you split it to workspace and const, but I don't think I should have added the pool allocation from the start)

```
int32_t tvmgen_default_run(TVMValue* args, int* type_code, int num_args, TVMValue* out_value, int* out_type_code, void* resource_handle) {
TVMValue tensors[4];
tensors[0] = ((TVMValue*)args)[0];
tensors[1] = ((TVMValue*)args)[1];
DLTensor global_const_workspace_dltensor = {
.data = &global_const_workspace
};
TVMValue global_const_workspace_tvm_value = {
.v_handle = &global_const_workspace_dltensor
};
tensors[2] = global_const_workspace_tvm_value;
DLTensor global_workspace_dltensor = {
.data = &global_workspace
};
TVMValue global_workspace_tvm_value = {
.v_handle = &global_workspace_dltensor
};
tensors[3] = global_workspace_tvm_value;
return tvmgen_default___tvm_main__((void*)tensors, type_code, num_args, out_value, out_type_code, resource_handle);
}
```

Comment (d-smirnov) [reply src/runtime/crt/aot_executor/aot_executor.c:209]: Thanks a lot @alanmacd.

**Review by d-smirnov — APPROVED** [review]

**Review by mehrdadh — APPROVED** [review]

**Comment by mehrdadh** [comment]
@alanmacd @d-smirnov thanks! this PR is merged.
